### ISSUE TITLE
please include the mysql database sql code

### ISSUE THREAD

**Issue by kalyan-gupta** [waqasraza123/simple-attendance-system-in-php--mysql--bootstrap-#2]

**Comment by waqasraza123** [comment]
@kalyan4786  you can create the database as per your requirements and modify the code accordingly, I am not managing this anymore.

**Comment by michael-milette** [comment]
@kalyan4786 , see the latest README.md documentation. As of right now, the latest update was applied today (Oct 24, 2017).
